from sklearn.cluster import KMeans as km
from gensim.models import Word2Vec as w2v
import numpy as np
import pickle as cp
from sklearn.externals import joblib
model = w2v.load('hi.bin')
km_model = joblib.load('model.pkl')
file = open('datakmalgo.txt')
data = []
line = file.readline().rstrip('\n')
while line != '':
    word = line.split(' ')[0].rstrip('\t0').rstrip('\t1').rstrip('\t')
    data.append(word)
    line = file.readline().rstrip('\n')
print(data)
words =[line.rstrip('\n') for line in file]
total=0
for word in data:
    try:
        t=model.wv[word]
        predicted= km_model.predict(np.asarray([model.wv[word]]))
        print(word,predicted)
        # print(predicted)

    except:
        total+=1
# for word in words:
#     pred = km_model.predict(np.asarray([model.wv[word]]))
#     print(pred)
#     print(word)
# pred = km_model.predict(np.asarray([model.wv['पत्ते']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['चिड़ियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['आँखें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['छात्र']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कहानी']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बुढ़िया']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['प्रतियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बात']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['पुस्तक']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['रुपया']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['भेड़']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['घोड़ा']]))
# print(pred)
# print("ceck1")
# pred = km_model.predict(np.asarray([model.wv['पत्ता']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बेटा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['लड़का']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['आँख']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['किताब']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बहन']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['तस्वीर']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['ऋतु']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बच्चा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कपड़ा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बात']]))
# print(pred)
# print("ceck2")
# pred = km_model.predict(np.asarray([model.wv['लड़के']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['आँखें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['किताबें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बहनें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['तस्वीरें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बच्चे']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कपड़े']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बातें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['पुस्तकें']]))
# print("ceck3")
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['रुपए']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कुत्ते']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बेटे']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['रास्ते']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['आँखे']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['पुस्तकें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['रातें']]))
# print("ceck4")
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बहनें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['नीतियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['घोड़े']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कक्षाएँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कमरे']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['वस्तुएँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['सेनाएँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बोलियाँ']]))
# print("ceck5")
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['चिड़ियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['घड़ियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['हड्डियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['छुट्टियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कमरा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['घोड़ा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कुत्ता']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बेटा']]))
# print("ceck6")
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['रास्ता']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['घर']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['घरों']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['डाकू']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बहन']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बांह']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['नीति']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['लिपि']]))
# print("ceck7")
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['गति']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['प्रति']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['नारी']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['चाबी']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['नदी']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['लता']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['वधू']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['वस्तु']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बहू']]))
# print("ceck8")
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बेटे']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['पुस्तकें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['रातें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बहनें']]))
# print(pred)
# print("ceck9")
# pred = km_model.predict(np.asarray([model.wv['पत्ते']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['चिड़ियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['आँखें']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['छात्र']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कहानी']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बुढ़िया']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['प्रतियाँ']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बात']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['पुस्तक']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['रुपया']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['भेड़']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['घोड़ा']]))
# print(pred)
# print("ceck10")
# pred = km_model.predict(np.asarray([model.wv['पत्ता']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बेटा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['लड़का']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['आँख']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['किताब']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बहन']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['तस्वीर']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['ऋतु']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बच्चा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['कपड़ा']]))
# print(pred)
# pred = km_model.predict(np.asarray([model.wv['बात']]))
# print(pred)
